### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by Junaid083** [Junaid083/Chat-App-Using-Socket-io#1]
While running project getting this error in console 

![image](https://github.com/Junaid083/Chat-App-Using-Socket-io/assets/122339731/2bd74710-97ee-4969-ba69-8b5b19052172)

**Comment by Junaid-Ali-712** [comment]
You need to clear all ports using `CLI`.
Then this wont appear again

**Comment by Junaid083** [comment]
Yeah that's helps thanks
